---
- name: Install nginx repo
  copy: src=etc-yum.repos.d-nginx.conf
        dest=/etc/yum.repos.d/nginx.conf
        owner=root
        group=root
        mode=0644
  tags: [ 'kibana' , 'yum' ]

- name: Install Packages
  yum: name={{ item }} state=present
  with_items:
    - nginx
    - unzip
    - git
  tags: [ 'kibana' , 'yum' ]

- name: Enable nginx
  service: name=nginx state=started enabled=yes
  tags: [ 'kibana' , 'yum', 'nginx' ]

- name: Get latest Kibana from GitHub
  git:  repo={{ kibana_git_url }}
        dest=/var/www/kibana
        version=master
        update=yes
  tags: [ 'kibana' , 'kibanaupdate']

- name: Configure kibana to point at ES
  lineinfile: "dest=/var/www/kibana/src/config.js state=present regexp='(^.*elasticsearch:.*:)(9200|443)(.*)$' line='    elasticsearch: \"https://\"+window.location.hostname+\":443\",'"
  tags: [ 'kibana' , 'kibanaconfig' , 'kibanaupdate' ]

- name: Copy nginx log rotation config
  copy: src=etc-logrotate.d-nginx dest=/etc/logrotate.d/nginx owner=root group=root mode=0644
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]

- name: Delete default nginx config
  file: dest=/etc/nginx/conf.d/{{ item }}
        state=absent
  with_items:
    - default.conf
    - example_ssl.conf
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]

- name: Copy main nginx config
  template: src=etc-nginx-nginx.conf.j2
            dest=/etc/nginx/nginx.conf
            owner=root
            group=root
            mode=0644
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]
  notify: restart nginx

- name: Copy nginx rewrite config
  template: src=etc-nginx-conf.d-rewrite.conf.j2
            dest=/etc/nginx/conf.d/rewrite.conf
            owner=root
            group=root
            mode=0644
  notify: restart nginx
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]

- name: Copy nginx SSL config
  template: src=etc-nginx-conf.d-ssl.inc.j2 dest=/etc/nginx/conf.d/ssl.inc owner=root group=root mode=0644
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]

- name: Copy nginx SSL public key
  copy: src={{ ansible_hostname }}_royall_com.crt dest=/etc/pki/tls/certs/{{ ansible_hostname }}_royall_com.crt owner=root group=root mode=0644
  notify: restart nginx
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]

- name: Copy nginx SSL private key
  template: src={{ ansible_hostname }}_royall_com.key.j2 dest=/etc/pki/tls/private/{{ ansible_hostname }}_royall_com.key owner=root group=root mode=0600
  notify: restart nginx
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]

- name: Copy kibana nginx config
  template: src=etc-nginx.conf.d-kibana.conf.j2 dest=/etc/nginx/conf.d/kibana.conf owner=root group=root mode=0644
  notify: restart nginx
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]

- name: Copy elasticsearch config
  template: src=elasticsearch.yml.j2
            dest=/etc/elasticsearch/elasticsearch.yml
            owner=root
            group=root
            mode=0644
  notify: restart elasticsearch
  tags: [ "kibana" , "kibanaconfig" ]

- name: Change ES heap size
  lineinfile: "dest=/etc/sysconfig/elasticsearch state=present regexp='^#?ES_HEAP_SIZE=' line='#ES_HEAP_SIZE=512m'"
  notify: restart elasticsearch
  tags: [ 'kibana' , 'kibanaconfig' , 'elasticsearch' ]
