---
- name: Install nginx repo
  copy: src=etc-yum.repos.d-nginx.repo
        dest=/etc/yum.repos.d/nginx.repo
        owner=root
        group=root
        mode=0644
  tags: [ 'kibana' , 'yum' ]

- name: Install Packages
  yum: name={{ item }} state=present
  with_items:
    - nginx
    - unzip
    - git
  tags: [ 'kibana' , 'yum' ]

- name: Get latest Kibana from GitHub
  git:  repo={{ kibana_git_url }}
        dest=/var/www/kibana
        version=development
        update=yes
  tags: [ 'kibana' , 'kibanaupdate']

- name: Configure kibana to point at ES
  lineinfile: "dest=/var/www/kibana/src/config.js state=present regexp='(^.*elasticsearch:.*:)(9200|443)(.*)$' line='    elasticsearch: \"https://\"+window.location.hostname+\":443\",'"
  tags: [ 'kibana' , 'kibanaconfig' , 'kibanaupdate' ]

- name: Configure kibana to use non-default route
  lineinfile: dest=/var/www/kibana/src/config.js regexp="^(.*default_route.*:)" line="\1 '{{kibana_default_route}}'," backrefs=true
  when: kibana_default_route is defined
  tags: [ 'kibana' , 'kibanaconfig' , 'kibanaupdate' ]

- name: Copy elasticsearch synthetic field script
  copy: src=kibana dest=/etc/elasticsearch/scripts/ owner=root group=root mode=0644 directory_mode=755
  tags: [ 'kibana' , 'kibanaconfig' ]

- name: Copy nginx log rotation config
  copy: src=etc-logrotate.d-nginx dest=/etc/logrotate.d/nginx owner=root group=root mode=0644
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]

- name: Delete default nginx config
  file: dest=/etc/nginx/conf.d/{{ item }}
        state=absent
  with_items:
    - default.conf
    - example_ssl.conf
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]

- name: Copy main nginx config
  template: src=etc-nginx-nginx.conf.j2
            dest=/etc/nginx/nginx.conf
            owner=root
            group=root
            mode=0644
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]
  notify: restart nginx

- name: Copy nginx rewrite config
  template: src=etc-nginx-conf.d-rewrite.conf.j2
            dest=/etc/nginx/conf.d/rewrite.conf
            owner=root
            group=root
            mode=0644
  notify: restart nginx
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]

- name: Copy nginx SSL config
  template: src=etc-nginx-conf.d-ssl.inc.j2 dest=/etc/nginx/conf.d/ssl.inc owner=root group=root mode=0644
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]
  notify: restart nginx

- name: Copy SSL public cert
  template: src=ssl_crt.j2 dest=/etc/pki/tls/certs/{{ kibana_ssl_cert_file | default(ansible_fqdn) }}.crt owner=root group=root mode=0644
  notify: restart nginx
  when: kibana_update_cert is defined
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]
  notify: restart nginx

- name: Copy SSL private key
  template: src=ssl_key.j2 dest=/etc/pki/tls/private/{{ kibana_ssl_key_file | default(ansible_fqdn) }}.key owner=root group=root mode=0600
  notify: restart nginx
  when: kibana_update_cert is defined
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]
  notify: restart nginx

- name: Copy kibana nginx config
  template: src=etc-nginx.conf.d-kibana.conf.j2 dest=/etc/nginx/conf.d/kibana.conf owner=root group=root mode=0644
  notify: restart nginx
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]
  notify: restart nginx

- name: Start and enable nginx
  service: name=nginx state=started enabled=yes
  tags: [ 'kibana' , 'yum', 'nginx' ]
