---
- name: Install Packages
  yum: name={{ item }} state=present
  with_items:
    - unzip
    - git
  tags: [ 'kibana' , 'yum' ]

- name: Get latest Kibana from GitHub
  git:
    repo={{ kibana_git_url }}
    dest=/var/www/kibana
    version=development
    update=yes
  tags: [ 'kibana' , 'kibanaupdate']

- name: Configure kibana to point at ES
  lineinfile: >
    dest=/var/www/kibana/src/config.js
    state=present
    regexp='(^.*elasticsearch:.*:)(9200|443)(.*)$'
    line='    elasticsearch: \"https://\"+window.location.hostname+\":443\",'
  tags: [ 'kibana' , 'kibanaconfig' , 'kibanaupdate' ]

- name: Configure kibana to use non-default route
  lineinfile: >
    dest=/var/www/kibana/src/config.js
    regexp="^(.*default_route.*:)"
    line="\1 '{{kibana_default_route}}',"
    backrefs=true
  when: kibana_default_route is defined
  tags: [ 'kibana' , 'kibanaconfig' , 'kibanaupdate' ]

- name: Copy elasticsearch synthetic field script
  copy:
    src=kibana
    dest=/etc/elasticsearch/scripts/
    owner=root
    group=root
    mode=0644
    directory_mode=755
  tags: [ 'kibana' , 'kibanaconfig' ]

- name: Copy kibana nginx config
  template:
    src=etc-nginx.conf.d-kibana.conf.j2
    dest=/etc/nginx/conf.d/kibana.conf
    owner=root
    group=root
    mode=0644
  notify: restart nginx
  tags: [ 'kibana' , 'nginx' , 'kibanaconfig' ]
