---
- name: Install nginx repo
  copy: src=etc-yum.repos.d-nginx.conf
        dest=/etc/yum.repos.d/nginx.conf
        owner=root
        group=root
        mode=0644
  tags:
    - kibana
    - yum

- name: Enable nginx
  service: name=nginx state=started enabled=yes
  tags:
    - kibana
    - nginx

- name: Install Packages
  yum: name={{ item }} state=present
  with_items:
    - nginx
    - unzip
    - git
  tags:
    - kibana
    - yum

- name: Get latest Kibana from GitHub
  git:  repo={{ kibana_git_url }}
        dest=/var/www/kibana
        version=master
        update=yes
  tags:
    - kibana

- name: Configure kibana to point at ES
  lineinfile: dest=/var/www/kibana/src/config.js
              state=present
              regex="elasticsearch: \"http://\".*,"
              line="elasticsearch: \"{{ es_url }}:{{ es_http_port }}\""
  tags:
   - kibana
   - config

- name: Copy nginx log rotation config
  copy: src=etc-logrotate.d-nginx dest=/etc/logrotate.d/nginx owner=root group=root mode=0644
  tags:
    - kibana
    - nginx
    - config

- name: Copy main nginx config
  template: src=etc-nginx-nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0755
  tags:
    - kibana
    - config
    - nginx
  notify: restart nginx

- name: Copy kiban nginx config
  template: src=etc-nginx.conf.d-kibana.conf.j2 dest=/etc/nginx/conf.d/kibana.conf owner=root group=root mode=0755
  tags:
    - kibana
    - config
    - nginx
  notify: restart nginx

- name: Copy kibana htpasswd file
  copy: src=htpasswd dest=/etc/nginx/conf.d/htpasswd owner=root group=root mode=0644
  tags:
    - kibana
    - config
